language: node_js
node_js:
- "10"

before_script:
- yarn install
script: yarn build

notifications:
  email:
    recipients:
    - harryemartland@gmail.com
    on_success: change
    on_failure: always

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master